### ISSUE TITLE
Show image to change at the start of the hour without refresh

### ISSUE THREAD

**Issue by finevans** [urfonline/frontend#63]
The emoji and the show name changes but the show image doesn't on the homepage

**Comment by brudil** [comment]
what browser? it should do

**Comment by finevans** [comment]
safari - haven’t tried it with any other browser!

On 13 Feb 2018, at 12:15, James Canning <notifications@github.com<mailto:notifications@github.com>> wrote:


what browser? it should do

**Comment by brudil** [comment]
Opps, yeah.
